### ISSUE TITLE
review server side (pre-check)

### ISSUE THREAD

**Issue by Derimarg** [Derimarg/code-command#41]
-make sure that graphql is working properly
- check server auth 
- Check queries
-  Check Resolvers
-  Check typeDefs

**Comment by ratalla816** [comment]
*CONFIG*
connection.js -OK
seeds.js - added course names to categories (lines 8-12):
                1.	Full Stack Web Application Development
                2.	Computer Science
                3.	Python
                4.	Cybersecurity
                5.	Digital Marketing
                6.	Bonus Courses 

                The products function starting on line 19 is where I will need to add the course names, I think..

*MODELS*
Category.js - OK
index.js - OK
Order.js - OK
Product.js - OK
User.js - OK

*SCHEMAS*
index.js - OK
resolvers.js - OK
typeDefs.js - OK

*UTILS*
auth.js - OK

*server.js - OK
